# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  database: xe
  host: 192.168.1.86
  username: dieid
  password: dieid
  port: 1521
  
production:
  adapter: oracle_enhanced
  database: xe
  host: 192.168.1.73
  username: DIEID_production
  password: dieid
  port: 1521

