development:
  adapter: oracle_enhanced
  database: xe
  host: 192.168.1.86
  username: dieid
  password: dieid
  port: 1521
  
production:
  adapter: oracle_enhanced
  database: xe
  host: 192.168.1.86
  username: DIEID_production
  password: dieid
  port: 1521

